services:
  flask-app:
    build: .
    container_name: practica-flask
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      FLASK_ENV: development
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: mi-secreto-super-seguro




